### PR TITLE
Add a ts declaration file

### PR DESCRIPTION
**Pull request by eliasparis**
Declaration file in order to use the module on typescript projects without compilator errors.

### CODE REVIEW

**Comment by eliasparis** [comment]
It has been a joy working with your library, so I thought it would be great to import it in some other TS projects as well.
Maybe it is not 100% complete but in my current projects it is working.

**Comment by ivantsov** [comment]
Hi @eliasparis, thanks for your interest in the project and the PR :)
I made a small refactoring of the PR, so can you please check that it works on your project?

**Comment by eliasparis** [comment]
Works perfect!

**Review by eliasparis — COMMENTED** [review]
👍

**Pull request merged**
